version: '3.9'

services:
  app:
    build: .
    container_name: tax-app
    depends_on:
      - db
    environment:
      DB_NAME: tax_estimator_user_details
      DB_USER: postgres
      DB_PASSWORD: Paker11242003#
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./app:/app
    command: python user_Authentication.py

  db:
    image: postgres:15
    container_name: tax-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Paker11242003#
      POSTGRES_DB: tax_estimator_user_details
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
